# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-24 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171124_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='notificacion',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='puntaje',
            field=models.IntegerField(blank=True, default=True),
        ),
    ]
