# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-24 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171124_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Notificacion',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='notificacion',
        ),
        migrations.AddField(
            model_name='servicio',
            name='notificacion_cuerpo',
            field=models.CharField(blank=True, default=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Servicio'),
        ),
    ]
