# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-24 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_servicio_notificacion_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociasubcategoria',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='notificacion_cuerpo',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='notificacion_titulo',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='puntaje',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
