# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-24 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20171124_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoria',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
