# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-24 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20171124_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serviciopedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Servicio / Pedido',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='servicio',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviciopedido',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Servicio'),
        ),
        migrations.AddField(
            model_name='serviciopedido',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Subcategoria'),
        ),
    ]
