# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-26 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20171124_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='subcategoria',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
