# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-26 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_subcategoria_subcategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoria',
            name='subcategoria',
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='descripcion',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
