# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-27 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_turnosocia_socia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sociadistrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Distrito')),
                ('socia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Socia')),
            ],
            options={
                'verbose_name': 'Socia/Distrito',
                'managed': True,
            },
        ),
    ]
