# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-27 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_sociadistrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='socia',
            name='numero_notificacion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
