# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-29 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_clientesocias'),
    ]

    operations = [
        migrations.AddField(
            model_name='socia',
            name='descripcion_notificacion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
