# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-29 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20171128_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='titulo_notificacion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
