# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-01 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20171201_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portadaphoto',
            name='nombre',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
