# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-01 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20171201_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='portadaphoto',
            name='effect',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='portadaphoto',
            name='loop',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='portadaphoto',
            name='speed',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
