# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-06 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20171201_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnosocia',
            name='turno',
        ),
        migrations.AddField(
            model_name='servicio',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
