# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-06 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20171206_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='static'),
        ),
    ]
