# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-07 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_cliente_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
