# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-07 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20171206_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fecha_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Fin'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Inicio'),
        ),
    ]
