# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-08 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20171206_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
