# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-09 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_cliente_distrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smsrecibidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('when', models.DateTimeField(blank=True, null=True)),
                ('sender', models.CharField(blank=True, max_length=1000, null=True)),
                ('receiver', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Sms Recibidos',
                'managed': True,
            },
        ),
    ]
