# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-13 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_smsrecibidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='latitud',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='longitud',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
