# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-20 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20171213_0812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': True, 'verbose_name': '1. Categoria'},
        ),
        migrations.AlterModelOptions(
            name='subcategoria',
            options={'managed': True, 'verbose_name': '2. Subcategoria'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
