# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-23 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_categoria_icono_seleccionado'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='referencia',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
