# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-25 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20180122_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiponotificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Tipo Notificacion',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='notificacion',
            name='cliente',
            field=models.ForeignKey(blank=True, max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Cliente'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tipo_notificacion',
            field=models.ForeignKey(blank=True, max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Tiponotificacion'),
        ),
    ]
