# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-25 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20180124_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiponotificacion',
            name='plantilla',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tiponotificacion',
            name='nombre',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
