# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-28 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20180124_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadosocia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Estado de Socia',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='socia',
            name='estado_socia',
            field=models.ForeignKey(blank=True, db_column='estado_socia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Estadosocia'),
        ),
    ]
