# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-29 00:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20180128_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'managed': True, 'ordering': ['-id'], 'verbose_name': 'Servicio'},
        ),
        migrations.RenameField(
            model_name='socia',
            old_name='correo',
            new_name='email',
        ),
    ]
