# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-11 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_categoria_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('photo', models.FileField(blank=True, null=True, upload_to='static')),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('icono', models.FileField(blank=True, null=True, upload_to='static')),
                ('icono_seleccionado', models.FileField(blank=True, null=True, upload_to='static')),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Menu',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': True, 'verbose_name': 'Categoria'},
        ),
    ]
